"""AI coaching report tab (optional feature; degrades gracefully)."""

from __future__ import annotations

import json

from PySide6.QtCore import QThread, Signal
from PySide6.QtWidgets import (
    QComboBox,
    QFileDialog,
    QHBoxLayout,
    QLabel,
    QPushButton,
    QTextEdit,
    QVBoxLayout,
    QWidget,
)

from ..analysis.workspace import Workspace
from ..config import AiConfig
from ..insights import create_provider
from ..insights.base import InsightResult
from ..insights.summary import build_summary

__all__ = ["InsightsView"]


class _Worker(QThread):
    finished_with = Signal(object)  # InsightResult

    def __init__(self, provider, summary: dict, parent=None):
        super().__init__(parent)
        self._provider = provider
        self._summary = summary

    def run(self) -> None:
        self.finished_with.emit(self._provider.generate(self._summary))


class InsightsView(QWidget):
    def __init__(self, workspace: Workspace, ai_config: AiConfig, parent=None):
        super().__init__(parent)
        self.workspace = workspace
        self.ai_config = ai_config
        self._worker: _Worker | None = None

        self.lap_combo = QComboBox()
        for i, label in enumerate(workspace.lap_labels()):
            if i != workspace.reference_index:
                self.lap_combo.addItem(label, userData=i)

        self.generate_button = QPushButton("Generate AI coaching report")
        self.generate_button.clicked.connect(self._generate_async)
        export_button = QPushButton("Export JSON summary…")
        export_button.clicked.connect(self._export_summary)

        self.status_label = QLabel(
            f"Endpoint: {ai_config.base_url} — model: {ai_config.model}"
            if ai_config.enabled
            else "AI insights disabled (enable in settings; everything else works without it)"
        )

        controls = QHBoxLayout()
        controls.addWidget(QLabel("Analyse lap:"))
        controls.addWidget(self.lap_combo)
        controls.addWidget(self.generate_button)
        controls.addWidget(export_button)
        controls.addStretch(1)

        self.report_edit = QTextEdit()
        self.report_edit.setReadOnly(True)
        self.report_edit.setPlaceholderText(
            "The report explains where and why you lose time vs the reference, "
            "and what to change — generated by your own local LLM."
        )

        layout = QVBoxLayout(self)
        layout.addLayout(controls)
        layout.addWidget(self.status_label)
        layout.addWidget(self.report_edit)

    # -- generation -----------------------------------------------------------

    def _current_lap_index(self) -> int:
        data = self.lap_combo.currentData()
        return int(data) if data is not None else self.workspace.reference_index

    def _summary(self) -> dict:
        return build_summary(self.workspace, self._current_lap_index())

    def _generate_sync(self) -> InsightResult:
        """Synchronous path (tests, scripting)."""
        result = create_provider(self.ai_config).generate(self._summary())
        self._show_result(result)
        return result

    def _generate_async(self) -> None:
        if self._worker is not None and self._worker.isRunning():
            return
        self.generate_button.setEnabled(False)
        self.report_edit.setPlainText("Generating report…")
        self._worker = _Worker(create_provider(self.ai_config), self._summary(), parent=self)
        self._worker.finished_with.connect(self._show_result)
        self._worker.finished.connect(lambda: self.generate_button.setEnabled(True))
        self._worker.start()

    def _show_result(self, result: InsightResult) -> None:
        self.report_edit.setPlainText(result.text)
        if result.ok:
            self.status_label.setText(f"Report by {result.model} via {result.provider}")
        elif result.error and result.error != "disabled":
            self.status_label.setText(f"Failed: {result.error}")

    def _export_summary(self) -> None:
        path, _ = QFileDialog.getSaveFileName(
            self, "Export analysis summary", "analysis_summary.json", "JSON (*.json)"
        )
        if path:
            with open(path, "w", encoding="utf-8") as f:
                json.dump(self._summary(), f, indent=2)
